
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/productdb
    username: user
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
